
apiVersion: v1
kind: deployment
metadata: 
  name: hello-world
  labels:
    app: my-app
    version: v1
    zone: prod
spec:
  replicas: 2
  selector:
    MatchLabels:
      app: my-app
  templet:
    matadata:
      label:
        app: my-app
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80

